---
grails:
    resources:
        pattern: '/**'
    nuevoPath:
        nuevo: 'apli/'
    profile: web
    codegen:
        defaultPackage: visor
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    controllers:
        upload:
            maxFileSize: 30000000
            maxRequestSize: 30000000
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    http:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB
server:
    session:
            timeout: 3600 #60 minutos
#        timeout: 60 #1 minuto

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 5000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://127.0.0.1:5432/visor_prod
#            url: jdbc:postgresql://50.116.33.232:5432/visorprod
            username: 'aqremmaq'
            password: 'remmaq'
#            username: aqremmaq
#            password: 'megan1963@'

        dataSources:
            visor:
                dbCreate: update
                url: jdbc:postgresql://127.0.0.1:5432/visor_prod
              #                url: jdbc:postgresql://50.116.33.232:5432/visorprod
                username: postgres
                password: 'postgres'

        grails:
            serverURL: http://localhost:8080
            #especificar una direccion IP para poder acceder desde otra computadora de la red
#            serverURL: http://192.168.100.3:8080
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://127.0.0.1:5432/visor_prod
    production:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://127.0.0.1:5432/visorprod
            username: aqremmaq
            password: 'meghan3963'

            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 10
                minIdle: 5
                maxIdle: 5
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
